#ifndef MEKD_MEs_Spin2_H
#define MEKD_MEs_Spin2_H


#include "gg_Spin2_2l.h"
#include "gg_Spin2_2lpA.h"
#include "gg_Spin2_OF.h"
#include "gg_Spin2_OFpA.h"
#include "gg_Spin2_SF.h"
#include "gg_Spin2_SFpA.h"
#include "gg_Spin2_2f_OF.h"
#include "gg_Spin2_2f_OFpA.h"
#include "gg_Spin2_2f_SF.h"
#include "gg_Spin2_2f_SFpA.h"
#include "qq_Spin2_DN_2l.h"
#include "qq_Spin2_DN_2lpA.h"
#include "qq_Spin2_DN_OF.h"
#include "qq_Spin2_DN_OFpA.h"
#include "qq_Spin2_DN_SF.h"
#include "qq_Spin2_DN_SFpA.h"
#include "qq_Spin2_2f_DN_OF.h"
#include "qq_Spin2_2f_DN_OFpA.h"
#include "qq_Spin2_2f_DN_SF.h"
#include "qq_Spin2_2f_DN_SFpA.h"
#include "qq_Spin2_UP_2l.h"
#include "qq_Spin2_UP_2lpA.h"
#include "qq_Spin2_UP_OF.h"
#include "qq_Spin2_UP_OFpA.h"
#include "qq_Spin2_UP_SF.h"
#include "qq_Spin2_UP_SFpA.h"
#include "qq_Spin2_2f_UP_OF.h"
#include "qq_Spin2_2f_UP_OFpA.h"
#include "qq_Spin2_2f_UP_SF.h"
#include "qq_Spin2_2f_UP_SFpA.h"
#include "Spin2_2l.h"
#include "Spin2_2lpA.h"
#include "Spin2_OF.h"
#include "Spin2_OFpA.h"
#include "Spin2_SF.h"
#include "Spin2_SFpA.h"
#include "Spin2_2f_OF.h"
#include "Spin2_2f_OFpA.h"
#include "Spin2_2f_SF.h"
#include "Spin2_2f_SFpA.h"



#endif
